Repository asdf-vm/asdf, pull requests merged in 2020-09, with the labels that each got.

#795 docs: link to Homebrew common issues from documentation site
  docs/core-manage-asdf-vm.md
Labels: enhancement

#803 Fix plugin-update --all when there are no plugins
  lib/commands/command-plugin-update.bash
Labels: bug

#798 chore: remove -vm from common usage as the tool is just asdf
  README.md
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/contributing-core-asdf.md
  docs/contributing-doc-site.md
  docs/core-manage-asdf.md
  docs/core-manage-plugins.md
  docs/core-manage-versions.md
  docs/index.html
Labels: proposal

#809 fix: docs file rename
  release/tag.sh
Labels: bug
