Repository asdf-vm/asdf, pull requests merged in 2020-06, with the labels that each got.

#700 fix: remove sort --version-sort from command-latest as list is already sorted
  lib/commands/command-latest.bash
Labels: bug

#740 docs: improve introduction and lift dependencies higher
  docs/core-manage-asdf-vm.md
Labels: enhancement

#737 fix: asdf shell command docs & help output
  docs/core-commands.md
  docs/core-manage-versions.md
  lib/utils.bash
  test/current_command.bats
  test/where_command.bats
Labels: WIP, enhancement

#742 docs: synchronize help text
  docs/core-commands.md
  help.txt
Labels: enhancement

#721 fix: remove `column` command in favor of awk
  lib/commands/command-plugin-list-all.bash
  lib/commands/command-plugin-list.bash
  test/plugin_list_all_command.bats
Labels: WIP, bug

#751 fix: CI formatting use editorconfig
  .github/workflows/workflow.yml
  bin/asdf
  completions/asdf.bash
  lib/asdf.sh
  lib/commands/command-export-shell-version.bash
  lib/commands/command-install.bash
  lib/commands/command-local.bash
  lib/commands/command-plugin-list.bash
  lib/commands/command-plugin-test.bash
  lib/utils.bash
Labels: bug
